[tool.poetry]
name = "dpd-db"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "db"}]

[tool.poetry.dependencies]
python = "^3.11"

sqlalchemy = "^2.0.0"
sqlalchemy-utils = "^0.39.0"
pysimplegui = "^4.60.4"
tqdm = "^4.64.1"
rich = "^13.3.1"
pandas = "^1.5.3"
openpyxl = "^3.1.0"
aksharamukha = "^2.1.2"
python-idzip = "^0.3.9"
mako = "^1.2.4"
markdown = "^3.4.1"
minify-html = "^0.10.8"
pip = "^23.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
