[tool.poetry]
name = "sqlite-db"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "dpd"}]

[tool.poetry.dependencies]
python = "^3.11"

sqlalchemy = "^2.0.0"
sqlalchemy-utils = "^0.39.0"
pysimplegui = "^4.60.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
