name: Draft Release

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install gdown
      run: pip install gdown

    - name: Download and unzip output_do.zip
      run: |
          # Replace 'your-file-id' with the actual ID of your file on Google Drive
          gdown --id '10bU9okbFmNKpCGF2sooQ5Bjh84qNkt9g' --output 'db/deconstructor/output_do.zip'
          unzip db/deconstructor/output_do.zip -d db/deconstructor/output_do

    - name: Test deconstructor/output/do
      run: |
          tree db/deconstructor || echo "tree command not found, using ls instead"
          ls -R db/deconstructor

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Config for GitHub release
      run: poetry run python scripts/config_github_release.py

    - name: Create dpd.db
      run: touch dpd.db

    - name: Build the database
      run: poetry run python scripts/db_rebuild_from_tsv.py

    - name: Run initial setup script
      run: poetry run bash scripts/bash/initial_setup_run_once.sh
    
    - name: Create version
      run: poetry run python tools/version.py

    - name: Create Inflections Templates
      run: poetry run python db/inflections/create_inflections_templates.py

    - name: Create Inflection Tables
      run: poetry run python db/inflections/generate_inflection_tables.py

    - name: Transliterate Inflections
      run: poetry run python db/inflections/transliterate_inflections.py

    - name: Update Sanskrit Family Roots
      run: poetry run python scripts/sanskrit_root_families_updater.py

    - name: Add Root Families
      run: poetry run python db/families/root_family.py

    - name: Add Word Families
      run: poetry run db/families/word_family.py
    
    - name: Add Compound Families
      run: poetry run python db/families/compound_family.py

    - name: Add Sets
      run: poetry run python db/families/sets.py

    - name: Add Idioms
      run: poetry run python db/families/idioms.py

    - name: Deconstructor Setup
      run: poetry run python db/deconstructor/sandhi_setup.py
        
    - name: Deconstructor Splitter
      run: poetry run python db/deconstructor/sandhi_splitter.py

    - name: Deconstructor Postprocess setup
      run: poetry run python db/deconstructor/sandhi_postprocess.py

    - name: Add Frequency
      run: poetry run python db/frequency/mapmaker.py

    - name: Test Dealbreakers
      run: poetry run python scripts/dealbreakers.py
           
    - name: Export Grammar Dictionary
      run: poetry run python exporter/grammar_dict/grammar_dict.py
    
    - name: Export GoldenDict & MDict
      run: poetry run python exporter/goldendict/export_gd_mdict.py

    - name: Export Deconstructor
      run: poetry run python exporter/deconstructor/deconstructor_exporter.py

    - name: Export Kindle & ePub
      run: poetry run python exporter/ebook/ebook_exporter.py

    - name: Zip GoldenDict & Mdict
      run: poetry run python scripts/zip_goldendict_mdict.py
           
    - name: Tarball DB
      run: poetry run python scripts/tarball_db.py
           
    - name: Summary
      run: poetry run python scripts/summary.py
 
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: "v0.0"
        release_name: "Draft Release"
        draft: true
        prerelease: false

    - name: Upload Asset dpd-goldendict.zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: exporter/share/dpd-goldendict.zip
        asset_name: dpd-goldendict.zip
        asset_content_type: application/zip

    - name: Upload Asset dpd-mdict.zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: exporter/share/dpd-mdict.zip
        asset_name: dpd-mdict.zip
        asset_content_type: application/zip

    - name: Upload Asset dpd-kindle.epub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: exporter/share/dpd-kindle.epub
        asset_name: dpd-kindle.epub
        asset_content_type: application/zip

    - name: Upload Asset dpd-kindle.mobi
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: exporter/share/dpd-kindle.mobi
        asset_name: dpd-kindle.mobi
        asset_content_type: application/zip

    - name: Upload Asset dpd.db.tar.bz2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: exporter/share/dpd.db.tar.bz2
        asset_name: dpd.db.tar.bz2
        asset_content_type: application/zip

